// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-RlYJfebkSSWW62B5LF-MFFtiQf2fDg',
    appId: '1:355584317331:web:b15b02d0cc3ba781b8ba66',
    messagingSenderId: '355584317331',
    projectId: 'testing-lms-146b1',
    authDomain: 'testing-lms-146b1.firebaseapp.com',
    storageBucket: 'testing-lms-146b1.appspot.com',
    measurementId: 'G-GB3897TD94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX1NL3gmB51l9HFpqBoR2n3brMBl0z9YI',
    appId: '1:355584317331:android:26ada4e67cdd46a6b8ba66',
    messagingSenderId: '355584317331',
    projectId: 'testing-lms-146b1',
    storageBucket: 'testing-lms-146b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3UBMxZ7bK07oTZsQI6e294b9mibLnbo',
    appId: '1:355584317331:ios:9e9e56975e53bbddb8ba66',
    messagingSenderId: '355584317331',
    projectId: 'testing-lms-146b1',
    storageBucket: 'testing-lms-146b1.appspot.com',
    iosBundleId: 'com.example.portal',
  );
}
